openapi: 3.0.1
info:
  title: CVU API
  description: CVU API documentation
  contact:
    name: Roberto Villarejo Martínez
    email: roberto.villarejo@comimsa.com
  license:
    name: MIT
  version: 0.0.1
servers:
  - url: https://cvu
tags:
  - name: cvu
    description: Cvu Resource
paths:
  /api/cvu/{cvu}:
    get:
      tags:
        - cvu
      summary: Obtiene una persona física por su número de CVU
      operationId: getPersonaFisicaByCvu
      parameters:
        - name: cvu
          in: path
          description: cvu
          required: true
          schema:
            type: string
        - name: tipo_usuario
          in: query
          description: El tipo de usuario
          required: false
          schema:
            $ref: "#/components/schemas/TipoUsuario"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaFisica"
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      deprecated: false
  /api/personas/{loginEmail}:
    get:
      tags:
        - cvu
      summary: Obtiene a una persona física por su correo de usuario
      operationId: getPersonaFisicaByEmail
      parameters:
        - name: loginEmail
          in: path
          description: loginEmail
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaFisica"
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      deprecated: false
  /api/rcea/{claveRcea}:
    get:
      tags:
        - cvu
      summary: Obtiene una persona física por su número RCEA
      operationId: getPersonaFisicaByRcea
      parameters:
        - name: claveRcea
          in: path
          description: claveRcea
          required: true
          schema:
            type: string
        - name: tipo_usuario
          in: query
          description: El tipo de usuario
          required: false
          schema:
            $ref: "#/components/schemas/TipoUsuario"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaFisica"
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      deprecated: false
  /api/reniecyt/{numeroReniecyt}:
    get:
      tags:
        - cvu
      summary: Obtiene una persona moral por su clave RENIECYT
      operationId: getPersonaMoralByReniecyt
      parameters:
        - name: numeroReniecyt
          in: path
          description: numeroReniecyt
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaMoral"
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      deprecated: false
components:
  schemas:
    Domicilio:
      title: Domicilio
      type: object
      properties:
        direccion:
          type: string
        tipo:
          type: string
    EntidadFederativa:
      title: EntidadFederativa
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
    Institucion:
      title: Institucion
      type: object
      properties:
        clave:
          type: string
        entidadFederativa:
          $ref: "#/components/schemas/EntidadFederativa"
        localidad:
          type: string
        municipio:
          type: string
        nombre:
          type: string
    PersonaFisica:
      title: PersonaFisica
      type: object
      properties:
        apellidoMaterno:
          type: string
        apellidoPaterno:
          type: string
        correo:
          type: string
        curp:
          type: string
        cvu:
          type: string
        domicilios:
          type: array
          items:
            $ref: "#/components/schemas/Domicilio"
        genero:
          type: string
        gradoAcademico:
          type: string
        instituciones:
          type: array
          items:
            $ref: "#/components/schemas/Institucion"
        login:
          type: string
        nacionalidad:
          type: string
        nivelAcademico:
          type: string
        nivelsni:
          type: string
        nombre:
          type: string
        paisResidencia:
          type: string
        rcea:
          type: string
        rfc:
          type: string
        telefono:
          type: string
        titulo:
          type: string
    PersonaMoral:
      title: PersonaMoral
      type: object
      properties:
        domicilio:
          type: string
        entidad:
          $ref: "#/components/schemas/EntidadFederativa"
        razonSocial:
          type: string
        reniecyt:
          type: string
        representantesLegales:
          type: array
          items:
            $ref: "#/components/schemas/PersonaFisica"
        rfc:
          type: string
        tipo:
          type: string
    TipoUsuario:
      type: string
      enum:
        - interno
        - externo
